### ISSUE TITLE
Remove visualisation code from code library

### ISSUE THREAD

**Issue by ricardoavelino** [BlockResearchGroup/compas_ags#103]
sure but also on the non-Rhino side it would be better to move this functionality to artists and objects of the plotter and/or viewer...

_Originally posted by @brgcode in https://github.com/BlockResearchGroup/compas_ags/pull/102#discussion_r573280577_

**Comment by juney-lee** [comment]
@ricardoavelino This comment has been "resolved," as [pull request #102](https://github.com/BlockResearchGroup/compas_ags/pull/102) was merged.
