### ISSUE TITLE
display - edge colors

### ISSUE THREAD

**Issue by juney-lee** [BlockResearchGroup/compas_ags#14]
Always draw the corresponding edges with matching colors (edge label dots and/or the edges themselves)

**Comment by brgcode** [comment]
need to think of a color scheme though, otherwise this might look a bit like a xmass tree...

**Comment by juney-lee** [comment]
One unnecessarily complicated way... would be to use two gradients: red gradient for tension, and blue gradient for tension.

**Comment by brgcode** [comment]
i would not overdo it with the colors. with better conventions for loads, and reactions vs internal members the diagrams will already quite legible and we could add some kind of mouse hovering conduit to identify corresponding elements...

**Comment by ricardoavelino** [comment]
Regarding colouring the diagrams, I think we could have (@duchaoyu):

Toogle option to show or not the edge labeling. By default I would leave this on.

Loads as green in form diagram and in the force diagram to help coresponding. Always on unchanged...

Dark Grey for the reactions, in the same away as the green for the loads.

Toogle option to activate tension and compression (blue, red). By default I would leave this off, but it is good to have it as an option.

I think this would be a good to do list to close this issue.

**Comment by brgcode** [comment]
@juney-lee can you add a document somewhere that describes the visual style of every element in a drawing?
a screenshot of an eq drawing with a bunch of arrows and descriptions is sufficient...

**Comment by ricardoavelino** [comment]
See issue #35
