### ISSUE TITLE
display - scale loaded edges in form diagram

### ISSUE THREAD

**Issue by juney-lee** [BlockResearchGroup/compas_ags#15]
The edges of the form diagram that are "externally loaded" should be scaled, so that it is visually identifiable and quantifiable. In GS, the default color for external loads is dark green.

**Comment by brgcode** [comment]
by scaled you mean that they should be thicker?

**Comment by juney-lee** [comment]
I was thinking about scaling the lines... But I guess the "correct" graphic statics way would be to keep them at same lengths in the form diagram, and draw the thickened and colored (green for loads, black or dark gray for reactions) line behind the loaded edges (similar to how we show thickened red and blues to show compression/tension). Maybe this will clutter the diagrams a bit. But at least, I think the edges representing the externally applied loads in both diagrams, should always appear green for legibility. I find the simple red/blue edge colors in the both diagrams make them super easy to read. 

![image.png](https://images.zenhubusercontent.com/5e26f82ce33c5e59629a8fa9/f36c8e9a-3b4f-4a7d-8dee-4997ef3af933)

**Comment by brgcode** [comment]
we should adhere religiously to the conventions established for gs drawings on equilibrium...

**Comment by juney-lee** [comment]
The only reason why I was thinking about scaling the loaded edges, is that it is usually part of the initial input, and if we just take the lengths of the loaded edges automatically as the q's, it makes manually setting them a bit less painful for more novice users...? Also maybe simplifies the scaling issue a bit (also maybe simplifies having to explain independent edges as a part of the workflow)? For example, if the loaded edge in the form diagram is drawn with a length of 1, then that edge in the force diagram will have length of 1. And then maybe once the force diagram has been created, all the loaded edges in the form diagram are drawn with equal lengths, per our convention.

**Comment by brgcode** [comment]
no scaling of load edges in the form diagram.
using lengths is just confusing because you have to factor in the scales of the diagrams.
furthermore, breaking with the conventions established in eQ (which were established for good reason) is also just confusing...

**Comment by ricardoavelino** [comment]
I also don't think the lengths of the edges in the form diagram should have any meaning. It can get confusing.

However, it is "logical" that the edges representing loads (`is_load:True`) and edges representing reactions (`is_reaction:True`) have their length always equal in the form diagram for visualisation and also hierarchy purpose.

We could "impose" the length equality after the first input from the user? Sounds a good idea?

**Comment by brgcode** [comment]
they should just be unit length. or some other scale factor that makes sense wrt to the scale of the diagram. this is something that could be user controlled...

**Comment by duchaoyu** [comment]
> I was thinking about scaling the lines... But I guess the "correct" graphic statics way would be to keep them at same lengths in the form diagram, and draw the thickened and colored (green for loads, black or dark gray for reactions) line behind the loaded edges (similar to how we show thickened red and blues to show compression/tension). Maybe this will clutter the diagrams a bit. But at least, I think the edges representing the externally applied loads in both diagrams, should always appear green for legibility. I find the simple red/blue edge colors in the both diagrams make them super easy to read.
> 
Changing the colors would be done. :) 
however, thickening the edges is kinda tricky in Rhino. A pipe is drawn (which would be a thickened edge from top view) to show compression / tension... and it looks like this. I'm a little bit unsure whether we should thicken all the edges.... 

> ![image.png](https://camo.githubusercontent.com/0af3a627ffff8a23bd5089c19d4bc2b3f8bbdbdb/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565323666383263653333633565353936323961386661392f66333663386539612d336234662d346137642d386465652d343939376566336166393333)

**Comment by ricardoavelino** [comment]
I will close the issue. In Rhino the pipes are the best way to visualise thicknesses. It is now pretty though. But I think it is what we have for now. It is already implemented.
