### ISSUE TITLE
display - update forces (labels) in force diagram after changing node

### ISSUE THREAD

**Issue by ricardoavelino** [BlockResearchGroup/compas_ags#19]
After some modification, the forces should be updated in the force-diagram. 

That is, the attribute edge['force'] should be updated in the ForceDiagram and in the visualisation on Rhino.

Usually these forces can be just calculated from the new "lengths" of the force diagram, but there is one special case when these "lengths" involves the length of the "loaded edge" = "independent edge". This is treated in issue #22.

**Comment by brgcode** [comment]
not entirely sure i understand the problem

**Comment by ricardoavelino** [comment]
This basically corresponds to recalculate the loads and redraw the force diagram with the updated values for the forces after a modification is executed in the force diagram.

This is a bug that should be resolved.

**Comment by ricardoavelino** [comment]
With new set up Scene() the refresh works properly. Closing...
