### ISSUE TITLE
Constraint on the moving of vertices in the Force Diagram due to "loaded edges"

### ISSUE THREAD

**Issue by ricardoavelino** [BlockResearchGroup/compas_ags#20]
When a loaded edge is present, this means that for some reason we need the force on the edge to be assigned as a specific value. Therefore, the movements on the force diagram can not be totally free anymore.

This becomes evident in the following case, in which the loaded edge = independent edge is the bold edge:

![Screenshot 2020-06-18 at 20.43.59.png](https://images.zenhubusercontent.com/5eeb7538a145580baa8a9291/7f00aa1f-9896-4027-8fe1-e988c96c064a)

Here, the node=2 has not the freedom to move freely. It needs to remain on the red circle, so the force remains constant in that edge.

Can we constraint the drag option in Rhino to respect that? How can we deal with the case in which many independents are possible? Should we allow the dragging and mark an error? 

Similar enhancements are also discussed in Issues #21 and #22.

**Comment by brgcode** [comment]
one should not be allowed to move any of the vertices on the load line in the force diagram. defining the orientation of loads is a responsibility of the form diagram!

**Comment by juney-lee** [comment]
One possible way would be to: 

Color the loaded edges green everywhere, so that it is obvious. Then, the vertices of all the green edges in the force diagram should not be allowed for vertex selection.

**Comment by brgcode** [comment]
agreed. furthermore, loads should be "symbols" with a standardised visual representation in the form diagram. direction and orientation can be changed by moving the load handle. magnitude has to be set as an attribute of the corresponding form diagram edge. loads cannot be manipulated in any way in the force diagram...

**Comment by ricardoavelino** [comment]
So this is a nice task for us @duchaoyu, display the edges corresponding to the loads in green, and display handles to modify the force diagram, just where we can perform freely the dragging. Maybe @juney-lee can help to define how this "symbols" should look like.

**Comment by ricardoavelino** [comment]
Summarised in issue #36.
