### ISSUE TITLE
Update possibilities for dragging the node based on constraints included in the form.

### ISSUE THREAD

**Issue by ricardoavelino** [BlockResearchGroup/compas_ags#21]
Following on the discussion from Issue #20 is an a very interesting feature would be to also limit the dragging to reflect additional constraints included on the form diagram. The discussion is on the image below.

![Screenshot 2020-06-18 at 20.43.59 copy.png](https://images.zenhubusercontent.com/5eeb7538a145580baa8a9291/5a239c29-aee3-44b5-9c2f-b882ee5b0289)

Adding constraint on vertex=0 limits the possibility to drag the point from the force diagram. Can we reflect these constraints interactively? There is also a learning purpose in understanding these constraints, that should be explored in the course. @juney-lee

**Comment by brgcode** [comment]
see my comment on #20

**Comment by ricardoavelino** [comment]
Summarised in issue #36.
