### ISSUE TITLE
Rescale Force Diagram after loaded edges have their length changed on the force diagram

### ISSUE THREAD

**Issue by ricardoavelino** [BlockResearchGroup/compas_ags#22]
In the same idea as issue #20. If we allow all the movements: 

- some of them would not work and return the message of fail on convergence...

- But, some would need a recalling of the force diagram, as discussion in the image:

![Screenshot 2020-06-18 at 20.44.24.png](https://images.zenhubusercontent.com/5eeb7538a145580baa8a9291/1fd32162-0885-48b6-b268-552e5dba8abb)

What is the most transparent way to deal with that? It is known that what we keep constant in the background is q_ind... Therefore, when the force is reduced to 0.78 its original value/length. q_ind keeps fixed so the length is also reduced by the same amount. 

My suggestion is that we alert the user and provide the option to rescale.

**Comment by brgcode** [comment]
one should not be allowed to move load line vertices in the force diagram. furthermore, there should be a clear distinction between the different components of a load.

* form diagram: line of action -> infinite line or ray
* form diagram: direction -> unit vector defined on line of action
* form diagram data structure: magnitude as attribute
* force diagram: line segment drawn based on info in form diagram

as you can see, only the form diagram should provide the possibility to change any of the properties related to loads...

**Comment by ricardoavelino** [comment]
Great.

Therefore, we must not allow for node=2 (force) to be selected and moved freely.

However, selection of the complete edge should be allowed (Selection of both node=2 and node=0) in the same movement to drag the edge force. This is irrelevant for this example, but will be relevant in other modifications...

**Comment by brgcode** [comment]
i would argue that the user moves the load line by moving the anchor point of the load line. this is visually also the clearest, since we can just draw that node and not the others...

**Comment by brgcode** [comment]
again, this is how it works in eQ and i think we should follow the "principle of least astonishment"

**Comment by brgcode** [comment]
https://en.wikipedia.org/wiki/Principle_of_least_astonishment

**Comment by ricardoavelino** [comment]
Ok, it makes sense and nice principle! Do you have an example of how this anchor point should look like? Is that supposed to be added in the "middle" of the edge?

**Comment by brgcode** [comment]
in the example at the top of this thread it is the vertex corresponding to the space to the right of the load :)

**Comment by ricardoavelino** [comment]
Summarised in issue #36.
