### ISSUE TITLE
Attributes on the FormDiagram to distinguish edges

### ISSUE THREAD

**Issue by ricardoavelino** [BlockResearchGroup/compas_ags#26]
The following attributes should be used to distinguish the edges. They should be explicit to the user:

`is_load` : If an edge is load
`is_reaction`: If an edge is reaction

When both are False, we have a internal edge.

**Comment by brgcode** [comment]
i would question whether we need to distinguish between the two. they are all just external and in fact, they will all always correspond to the leaves of the diagram. so we might not have to mark them at all...

**Comment by ricardoavelino** [comment]
That's a good point. The difference is that we expect the user to input the load value to the ones marked as `is_load`. It is also easier to explain. For now I would keep both attributes. For calculation purposes, we can always use `form.leaves()` and get all of them.

**Comment by duchaoyu** [comment]
compas_ags\src\compas_ags\diagrams\formdiagram.py

```
        self.update_default_edge_attributes({
            'q': 1.0,
            'f': 0.0,
            'l': 0.0,
            'is_ind': False,
            'is_element': False,
            'is_reaction': False,
            'is_load': False,
            'is_edge': True,
            **'is_external': False,**
        })
```
```
    def external_edges(self):
        external_edges = []
        leaves = self.leaves()
        for i, (u, v) in enumerate(self.edges_where({'is_edge': True})):
            if u in leaves or v in leaves:
                external_edges.append((u, v))
                self.edge_attribute((u, v), 'is_external', True)
        return external_edges
```

**Comment by ricardoavelino** [comment]
They are not distinguished anymore.
