### ISSUE TITLE
display - update artist when form/force diagram has been updated

### ISSUE THREAD

**Issue by duchaoyu** [BlockResearchGroup/compas_ags#29]
```
form = FormDiagram.from_graph(graph)
formartist = FormArtist(form, layer='FormDiagram')
formartist.draw_diagram()
```

after a form diagram is modified, such as assigning q to edges, redrawing the formaritst doesn't update these attributes. 
so instead of redraw, 
`formartist.draw_diagram()`
I always make a new artist... I'm not sure whether it's a correct way. 
formartist = FormArtist(form, layer='FormDiagram')
formartist.draw_diagram()

**Comment by ricardoavelino** [comment]
Solved with Scene()
