### ISSUE TITLE
move vertices, allow ortho

### ISSUE THREAD

**Issue by duchaoyu** [BlockResearchGroup/compas_ags#30]
There's a bug when we try to move vertices in forcediagram. the points cannot move orthogonally. 
`GetPoint.PermitOrthoSnap` is already True, However, this function seems to be inactivated in `OnDynamicDraw` . I don't know how it's realized in RV2 (check the code and cannot find it...)

**Comment by duchaoyu** [comment]
![image](https://user-images.githubusercontent.com/43376817/85851843-c033c700-b7af-11ea-9edd-bb515cf056c0.png)

**Comment by ricardoavelino** [comment]
I have the same issue

**Comment by ricardoavelino** [comment]
Solved with new form and force objects.
