### ISSUE TITLE
automatic calculation of force diagram scale

### ISSUE THREAD

**Issue by duchaoyu** [BlockResearchGroup/compas_ags#32]
After updating the forcediagram(1), the formdiagram is drawn, then the forcediagram is redrawn(2). 
This issue is relevant to issue #29 
The method we draw the forcediagram currently is always dependent on formdiagram. Thus, when the formdiagram is updated, the forcediagram is scaled by a different scale factor. So if issue 29 is solved, we could use the same scale factor, which is an attribute of the forcediagram... 
Another solution that may be used before issue 29 is to save this scale factor and use it robustly...

**Comment by ricardoavelino** [comment]
Scalling and anchoring the force diagram is much clearer now.

@duchaoyu to include a pull request with a "suggested" scale that could be automatically set before the force diagram is drawn.

(@duchaoyu please refer to this issue in the pull request 😉)

**Comment by duchaoyu** [comment]
this is solved ?

**Comment by duchaoyu** [comment]
@ricardoavelino it works well on your pc?

**Comment by ricardoavelino** [comment]
Yes, this is done. Closing.
