### ISSUE TITLE
collapsed edges in the force diagram have no orientation

### ISSUE THREAD

**Issue by duchaoyu** [BlockResearchGroup/compas_ags#33]
In exercise question 6 and 7, if I modify the forcediagram, and make two vertices overlap, which means the edge length is zero, then I always cannot compute the FormDiagram. Unsure whether it's a limitation of AGS or a bug. 

![image](https://user-images.githubusercontent.com/43376817/86537265-1ad6cc80-beee-11ea-856a-858b74a80d07.png)

![image](https://user-images.githubusercontent.com/43376817/86537215-9d12c100-beed-11ea-962e-073aa5ea807a.png)

**Comment by ricardoavelino** [comment]
@brgcode this is still not possible with the new code. 

Everytime that one edge goes to zero its "orientation" stops existing (a zero vector does not point anywhere) and this is an issue with the current formulation.

We would like to explore this example in class, therefore, do you have any suggestion for us? The only solution in here is redrawing the form diagram removing the member which force collapsed to zero. Can you think of an automated way to do that?

Thanks.

**Comment by juney-lee** [comment]
For any edge that has collapsed to a point in the force diagram, we could assign a dummy orientation vector of (0,0,1)?

**Comment by brgcode** [comment]
what is the problem with the orientation? where exactly does this fail?

**Comment by ricardoavelino** [comment]
The "problem" is that we can not make the force goes to zero, i.e. make the edge in the force diagram have zero length.

**Comment by brgcode** [comment]
yes, i understood that, but where/how/what goes wrong? you mentioned something about the orientation being the "problem" ...

**Comment by brgcode** [comment]
i think this is now solved. please check and close if appropriate
