### ISSUE TITLE
Reaction Forces - drawing

### ISSUE THREAD

**Issue by duchaoyu** [BlockResearchGroup/compas_ags#34]
When draw lines for FormDiagram, it needs to be clearify that all supports should draw a reaction force from x and y direction if we need to run bi-ags. (As all the examples in bi-ags. )

![image](https://user-images.githubusercontent.com/43376817/86894248-1800f500-c103-11ea-85f7-955c16cfbf88.png)

If the FormDiagram is drawn as a hinge and a roller (3 lines), or only vertical reaction forces( 2 lines) we would get the following error when running the newton method to update FormDiagram from ForceDiagram...
![image](https://user-images.githubusercontent.com/43376817/86895005-269bdc00-c104-11ea-9f2f-537efec5356c.png)
![image](https://user-images.githubusercontent.com/43376817/86895021-2bf92680-c104-11ea-923b-72b67fcac828.png)
 
![image](https://user-images.githubusercontent.com/43376817/86894813-e3416d80-c103-11ea-913a-756acb0c504b.png)

**Comment by ricardoavelino** [comment]
When the isostatic boundary conditions are considered (roller in one side and x,y fixed) ags2 can't deal with the right to left modification (force to form). This does not occur in ags form from force modification. We may need to review this topic in the future reincorporating ags2. However, for now I will close it.
