### ISSUE TITLE
dynamically display corresponding element labels

### ISSUE THREAD

**Issue by ricardoavelino** [BlockResearchGroup/compas_ags#35]
Recovering the discussion from #14 I think that a conduit to identify the edges can be really beneficial to visualise the diagrams. I will close the previous issue.

**Comment by juney-lee** [comment]
This could be resolved with an "inspector" functionality, with a toggle for on/off in settings.

**Comment by duchaoyu** [comment]
I would try today

**Comment by ricardoavelino** [comment]
<img width="580" alt="image" src="https://user-images.githubusercontent.com/36137188/88968044-13a0a580-d285-11ea-92c0-dbc6a6dba3d2.png">

It would be interesting to add the option of "clicking in a node" or "clicking in an edge" and highlight the force, as in the image above.

**Comment by brgcode** [comment]
shall i give this a go or do you guys already have something?

**Comment by duchaoyu** [comment]
No, not yet...

**Comment by brgcode** [comment]
okay i will try something then

**Comment by ricardoavelino** [comment]
done
