### ISSUE TITLE
Future Feature: Remove handles for certain edges in the force diagram

### ISSUE THREAD

**Issue by ricardoavelino** [BlockResearchGroup/compas_ags#36]
This issue summarises #20 #21 #22. If possible, we should restrict movements on the force diagram.

The simplest way to do that is to remove handles (points) from the end of the lines that represents applied loads in a force diagram. This could be simply done by restricting movement to the lines in the force diagram that are associated with leaves in the form diagram.

However, attention should be paid to some cases where these leaves represent reactions in hyper-static schemes.

(Another layer of this is discussed in issue #21, where more geometrical constraints would apply to the force diagram but this is too much for compas_ags and is better implemented in a drawing tool like geogebra.)

**Comment by juney-lee** [comment]
@ricardoavelino I believe that this has been resolved with the first release of RhinoGS a while back. Although, more enhancements and improvements coming, related to this issue regarding controlled interactivity with constrained elements.
