### ISSUE TITLE
possibility to "work and keep" different form diagrams 

### ISSUE THREAD

**Issue by ricardoavelino** [BlockResearchGroup/compas_ags#41]
We have noted that once we work with one form diagram, even If we save as the layers `AGS::FormDiagram` and `AGS::ForceDiagram` with a different name, say `AGS-trial_1::...` the diagrams get deleted once we initiate a new structure. 

How can we create a mechanism that keep such info there and allow a user to work and store the diagrams in different layers, like it is done in RV2?

**Comment by juney-lee** [comment]
Simply copying the objects and putting them on a different layer will make a detached copy of the diagrams. AGS::... layers should be used for only one active set of diagrams.

**Comment by brgcode** [comment]
just as background info.

the "main" layers get cleared automatically when the scene is updated. in addition, every drawing command keeps track of the guids of the rhino objects it creates. the next time this command is run, those guids will be used to delete the previously drawn objects. 

indeed, by making a copy, the guid changes and the objects will not be deleted...

**Comment by brgcode** [comment]
i have the feeling this is in fact a non-issue :) so i will close it...

**Comment by ricardoavelino** [comment]
Hello. Me and @duchaoyu tried and this does not work somehow. Could you try on your side? 

Even if we save the "mother-layer" with a different name and we use the commands `AGS_load_session` or `AGS_init` to start over the diagram from before gets deleted.

**Comment by brgcode** [comment]
you have to make a copy of the objects and put them in a different layer. this works fine for me. please try again...

**Comment by juney-lee** [comment]
This also works for me. @ricardoavelino maybe you are trying to describe something else? Let's discuss in person if you still have issues.

**Comment by brgcode** [comment]
just FYI, renaming the layer is not enough. you have to actually make a copy of the objects. otherwise their GUIDs are the same, regardless of the layer they are in...
