### ISSUE TITLE
toolbar implementation

### ISSUE THREAD

**Issue by ricardoavelino** [BlockResearchGroup/compas_ags#57]
for organisation purposes, this highlights that some hours will be necessary to put a toolbar in place for compas_ags in rhino

**Comment by juney-lee** [comment]
I tried a first pass at reorganizing the menu and toolbar, cleaned up and simplified some commands. Tried to keep a similar structure/approach as RV2, to have some organizational/structural/visual consistency; menu is a bit more clustered, but the toolbar buttons are much more explicit and correspond to the workflow (from left to right). Basically, if you press every button on the toolbar from left to right, the user should be able to get a simple setup running without modifying any optional parameters. As we have experienced with RV2, this will probably take a few rounds of testing to fine-tune! Just a first pass...

@ricardoavelino @duchaoyu Please pull this UI update, test, update any unpulled pull requests, etc.

![image.png](https://images.zenhubusercontent.com/5e26f82ce33c5e59629a8fa9/170fa3cb-c143-4e99-820c-4258a488525f)

![image.png](https://images.zenhubusercontent.com/5e26f82ce33c5e59629a8fa9/109fb20d-85f6-4def-b756-7e1bce9037e8)

**Comment by ricardoavelino** [comment]
For the rehearsal the best option to have RV2 and AGS toolbar at the same is the creation of an environment `gs` installing all the packages here https://app.gitbook.com/@blockresearchgroup/s/rv2/documentation/dev-install plus compas_ags I suppose

**Comment by ricardoavelino** [comment]
I tested the toolbar, but I think there's an issue with the compas version related to classes `VertexModifier` and `EdgeModifier` that I could not solve. I think we better check with @brgcode and update compas_ags accordingly.

**Comment by ricardoavelino** [comment]
Toolbar V1 is out there thanks to @juney-lee we can close this issue
