### ISSUE TITLE
Deal with exceptions

### ISSUE THREAD

**Issue by ricardoavelino** [BlockResearchGroup/compas_ags#66]
I noticed that when there's an error in the calculation, as for example, no independent are selected (no assigned forces), or even if the modification in the force diagram result in an error of this sort. How should we overcome this? Perhaps if the functions `form_from_qid` and `force_from_form` throw an exception this would do? and we can show the user a proper message?

<img width="609" alt="image" src="https://user-images.githubusercontent.com/36137188/90680459-3eed3380-e238-11ea-994c-df8f4fc7d1ed.png">

**Comment by brgcode** [comment]
this is now indirectly solved...
