### ISSUE TITLE
Display settings button/menu

### ISSUE THREAD

**Issue by ricardoavelino** [BlockResearchGroup/compas_ags#70]
Currently our display settings button is quite overwhelming, with 5 additional options.

I suggest we slowly move this information to a "pop-up" box as in rv2, with at least 3 tabs. Two for form/force and one general settings tab. Here is the reference:

<img width="476" alt="image" src="https://user-images.githubusercontent.com/36137188/91448653-88e5a300-e850-11ea-8662-d399969f897c.png">

Here are some thoughts on what could be on it. We can use this issue as channel discussion.

I would also definitely take out the options "Move Form / Force diagrams" out of this button. For me it makes sense to create a button "Move" with options Form/ Force / Both.

FormObject
> Visualisation
>> edge-label: T/F
>> force-label: T/F
>> vertex-label: T/F
>> show-pipes: T/F

> Scale
>> pipes-scale: [float]

> Color
>> ind-edges-color: set color
>> leaf edges-color: set color
>> compression/tension: T/F
>> if compression/tension == False allows for changing:
>> edge-label-color: set color
>> vertex-label-color: set color

ForceObject
> Visualisation
>> edge-label: T/F
>> force-label: T/F
>> vertex-label: T/F

> Scale
>> diagram-scale: [float]

> Color
>> ind-edges-color: set color <this needs to be common to form/force>
>> leaf edges-color: set color <this needs to be common to form/force>
>> compression/tension: T/F
>> if compression/tension == False allows for changing:
>> edge-label-color: set color
>> vertex-label-color: set color

AGS
> Solver
>> Autoupdate: T/F

> Warnings
>> show deviations: T/F <This could help while moving the force diagram>

**Comment by brgcode** [comment]
yes, i agree (in principle, i haven't looked at your proposal). we should also provide a table with structural information rather than showing forces in labels. labels should be used as little as possible

**Comment by brgcode** [comment]
can you maybe file another issue for the structural info tables?
