### ISSUE TITLE
Move/Drag Diagrams Button

### ISSUE THREAD

**Issue by ricardoavelino** [BlockResearchGroup/compas_ags#71]
I suggest also take out the options "Move Form / Move Force diagrams" out of display settings button. 

For me it makes sense to create a button `Move Diagrams` with options `Form/ Force / Both`. 

This button could be called: `Drag Diagrams` to avoid confusion with `Move nodes`. But then this is an English decision, does "drag diagram" sounds good in your opinion?

**Comment by brgcode** [comment]
i would suggest that we leave the toolbar for what it is for now, and focus on commands and functionality. juney can pick up the toolbar development again next week...

**Comment by ricardoavelino** [comment]
move is available in menu
