### ISSUE TITLE
Provide table with structural info about forces

### ISSUE THREAD

**Issue by ricardoavelino** [BlockResearchGroup/compas_ags#72]
we should provide a table with structural information about the structure's forces.

labels should be used as little as possible.

_Originally posted by @brgcode in https://github.com/BlockResearchGroup/compas_ags/issues/70#issuecomment-681969790_

**Comment by duchaoyu** [comment]
A table provides all structure information. 
The user could click a row in the table, and thecorresponding edge in the FormDiagram would be highlighted. 
@ Li Chen

**Comment by ricardoavelino** [comment]
done
