### ISSUE TITLE
inspector

### ISSUE THREAD

**Issue by duchaoyu** [BlockResearchGroup/compas_ags#75]
Inspectors would hint the user the duality of FormDiagram and ForceDiagram: edge - edge, node - face, face - node. 
Inspectors would work either by user moving the mouse on the object (which might not work perfectly with overlapping objects), or by selecting the object manually.

**Comment by duchaoyu** [comment]
This issue would replace issue #35

**Comment by ricardoavelino** [comment]
I think that to avoid the problem of overlapping, this command should always ask to click.

**Comment by ricardoavelino** [comment]
done
