### ISSUE TITLE
force to form issues

### ISSUE THREAD

**Issue by tkmmark** [BlockResearchGroup/compas_ags#8]
I have generated this Force diagram by solving an input Form diagram (representing a basic truss) with specific load and Q values using AGS.

**graphstatics.form_update_q_from_qind(form)
graphstatics.force_update_from_form(force, form)**

![image](https://user-images.githubusercontent.com/9421670/43865015-90324f70-9b61-11e8-8a47-98ee5af66da8.png)

I have verified the Force diagram manually, and confirmed that both diagrams are reciprocal.  Thus one would expect that generating a Form again from this diagram will yield no changes at all.  However, this is not the case: 

**graphstatics.form_update_from_force(form, force)**

![image](https://user-images.githubusercontent.com/9421670/43865137-f43fb700-9b61-11e8-82eb-ee7791e06eae.png)

*please ignore the edge direction in the Form diagrams.  It shows the edge direction, not necessarily the loading directions.

**Comment by brgcode** [comment]
can you post the script as a gist so i can have look?

**Comment by juney-lee** [comment]
@brgcode @tkmmark this seems super old... resolved now, I assume?

**Comment by ricardoavelino** [comment]
With root finding this should be solvable. 

We could give it a try, if it is still relevant to @tkmmark.

**Comment by tkmmark** [comment]
@ricardoavelino @juney-lee 
Yes this is very old indeed.
There were issues with 0-force members and sign changes (with tension elements) back then... think those problems are now more or less resolved now.  Close away.
