### ISSUE TITLE
feature request: more explanation or referencing in documentation

### ISSUE THREAD

**Issue by tkmmark** [BlockResearchGroup/compas_ags#95]
It would be helpful if the documentation can provide more references (as is sort of the case in compas) to supplement the sparse descriptions currently found in the documentation for explaining the various formulations...

so for instance..
**Update form from force...**
https://docplayer.net/21072949-Least-squares-intersection-of-lines.html
(Interactive Vault Design: equation 7-10)

**Update force from form**
Algebraic graphic statics: equation 10

**Comment by juney-lee** [comment]
The compas GS packages are in the process of being documented, compas_ags included. Thanks for the reminder! Please do point out any other functions or algorithms that needs particular attention in being explained with additional images/text, or ones you would like to see explained in more detail.

**Comment by juney-lee** [comment]
@tkmmark The online documentation for compas_ags is being overhauled and will be available as an official GitBook page soon.
