### ISSUE TITLE
spelling consistency

### ISSUE THREAD

**Issue by tkmmark** [BlockResearchGroup/compas_ags#96]
again... due to the fateful decision to use the spelling of the revolutionists (see [#127](https://github.com/compas-dev/compas/issues/127))... all instances of 'parallelise' should become, alas, 'parallelize'.  ditto for 'optimise_loadpath'.

**Comment by juney-lee** [comment]
@ricardoavelino If there are any, could you update the spelling convention in a pull request? Also something to keep in mind for future developments for compas_ags, and in general.
